### ISSUE TITLE
Add Arroyo to the list

### ISSUE THREAD

**Issue by prrao87** [rewrite-bigdata-in-rust/RBIR#12]
I've been following the progress of the Arroyo project (distributed stream processing engine built in Rust) that's meant to be a Rust alternative to Flink - is there a reason it's not included here? Just wanted to point this out. Thanks!
https://github.com/ArroyoSystems/arroyo

**Comment by Xuanwo** [comment]
> is there a reason it's not included here? 

Just not know about it. Happy to see such projects exist.

Would you like to start a PR for this? I will happy to merge it.

**Comment by prrao87** [comment]
Great, I just did. And thank you for setting this up! I've been following your work and your blog, and it's a really great initiative. Happy to join in this effort and support open source 🚀 +  Rust 🦀.

**Comment by Xuanwo** [comment]
> Great, I just did. And hank you for setting this up! I've been following your work and your blog, and it's a really great initiative. Happy to join in this effort and support open source 🚀 + Rust 🦀.

Thanks a lot for the kind words. Let's rock!
