### ISSUE TITLE
Update "About" section in repository description

### ISSUE THREAD

**Issue by prrao87** [rewrite-bigdata-in-rust/RBIR#30]
The "About" section of this repo doesn't have a description:

> No description, website, or topics provided.

Could we update it to something like this?

> A collection of Rust projects in the Big Data Ecosystem, and how to get started contributing.

**Comment by Xuanwo** [comment]
Thanks a lot for catching this!

Updated to: `A collection of RBIR projects and posts for anyone interested in joining this journey.`
