### ISSUE TITLE
New project application list

### ISSUE THREAD

**Issue by liugddx** [rewrite-bigdata-in-rust/RBIR#6]

**Comment by liugddx** [comment]
How about adding the rust sdk of milvus . https://github.com/milvus-io/milvus-sdk-rust

**Comment by Xuanwo** [comment]
This issue prompted us to reconsider the scope of RBIR. Perhaps we should remove all SDK-related items. `iceberg-rust` and `paimin-rust` are different as they are implementations themselves, but `ceph-rust` and `milvus-sdk-rust` are merely SDKs that still depend on a C++ codebase server.

Let me remove `ceph-rust` instead.

**Comment by liugddx** [comment]
> This issue prompted us to reconsider the scope of RBIR. Perhaps we should remove all SDK-related items. `iceberg-rust` and `paimin-rust` are different as they are implementations themselves, but `ceph-rust` and `milvus-sdk-rust` are merely SDKs that still depend on a C++ codebase server.
> 
> Let me remove `ceph-rust` instead.

Got it.

**Comment by Xuanwo** [comment]
Thank you! Let's close.
